/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yoav;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test void appHasAGreeting() {
        TCPClient tcp = new TCPClient();
        tcp.openConnection();
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assert(true);
    }
}
